# Generated by Django 5.2.12 on 2026-03-09 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this alert (UUID v4, auto-generated).', primary_key=True, serialize=False)),
                ('alert_type', models.CharField(help_text="Analyzer key that produced this alert (e.g. 'large_transaction').", max_length=100)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], help_text='Severity level: LOW, MEDIUM, or HIGH.', max_length=20)),
                ('message', models.TextField(help_text='Human-readable explanation of why this alert was raised.')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', help_text='Lifecycle status: OPEN (default) → ACKNOWLEDGED → RESOLVED.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this alert record was created. Set automatically.')),
                ('organization', models.ForeignKey(help_text='The organization this alert is scoped to.', on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
