# Generated by Django 5.2.12 on 2026-03-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='reported',
            field=models.BooleanField(db_index=True, default=False, help_text='True once this alert has been included in a generated report'),
        ),
    ]
