# Generated by Django 5.2.12 on 2026-03-20 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_reported'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='report_run',
            field=models.ForeignKey(blank=True, help_text='The ReportRun that has claimed this alert for inclusion in a report. NULL means unclaimed and available for the next report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_alerts', to='reports.reportrun'),
        ),
    ]
