# Generated by Django 5.2.12 on 2026-03-09 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this transaction (UUID v4, auto-generated).', primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Calendar date on which the transaction occurred.')),
                ('vendor', models.CharField(db_index=True, help_text="Name of the vendor or counterparty (e.g. 'AWS', 'Stripe').", max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text="Transaction amount in the organization's currency. Must be positive.", max_digits=14)),
                ('description', models.TextField(blank=True, default='', help_text='Optional free-text description of the transaction.')),
                ('category', models.CharField(blank=True, default='', help_text="Optional category label (e.g. 'SaaS', 'Payroll', 'Revenue').", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was inserted. Set automatically.')),
                ('organization', models.ForeignKey(help_text='The organization this transaction belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'date'], name='tx_org_date_idx'), models.Index(fields=['vendor', 'amount', 'date'], name='tx_vendor_amount_date_idx')],
            },
        ),
    ]
