# Generated by Django 5.2.12 on 2026-03-18 21:00

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('transactions', '0002_add_amount_positive_constraint'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE transactions_transaction SET date = CURRENT_DATE WHERE date > CURRENT_DATE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('date__lte', django.db.models.functions.datetime.Now())), name='transaction_date_not_future'),
        ),
    ]
