import uuid

from django.db import models

from apps.organizations.models import Organization


class Alert(models.Model):
    """
    Represents a risk alert generated by an Analyzer for an Organization.

    Alerts are created automatically by ``AlertService`` after each analysis
    run. They progress through a simple lifecycle:
        OPEN → ACKNOWLEDGED → RESOLVED

    Design notes:
    - ``alert_type`` mirrors the analyzer key (e.g. ``"large_transaction"``).
    - ``severity`` drives downstream triage (HIGH alerts may page on-call).
    - ``status`` is intentionally narrow — no deletion, only state transitions.
    """

    class Severity(models.TextChoices):
        LOW = "LOW", "Low"
        MEDIUM = "MEDIUM", "Medium"
        HIGH = "HIGH", "High"

    class Status(models.TextChoices):
        OPEN = "OPEN", "Open"
        ACKNOWLEDGED = "ACKNOWLEDGED", "Acknowledged"
        RESOLVED = "RESOLVED", "Resolved"

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier for this alert (UUID v4, auto-generated).",
    )
    organization = models.ForeignKey(
        Organization,
        on_delete=models.PROTECT,
        related_name="alerts",
        help_text="The organization this alert is scoped to.",
    )
    alert_type = models.CharField(
        max_length=100,
        help_text="Analyzer key that produced this alert (e.g. 'large_transaction').",
    )
    severity = models.CharField(
        max_length=20,
        choices=Severity.choices,
        help_text="Severity level: LOW, MEDIUM, or HIGH.",
    )
    message = models.TextField(
        help_text="Human-readable explanation of why this alert was raised.",
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.OPEN,
        help_text="Lifecycle status: OPEN (default) → ACKNOWLEDGED → RESOLVED.",
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when this alert record was created. Set automatically.",
    )
    reported = models.BooleanField(
        default=False,
        db_index=True,
        help_text="True once this alert has been included in a generated report",
    )

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Alert"
        verbose_name_plural = "Alerts"

    def __str__(self) -> str:
        return f"[{self.severity}] {self.alert_type} — {self.status}"
