# Generated by Django 5.2.12 on 2026-03-09 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this audit log entry (UUID v4, auto-generated).', primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text="Machine-readable event identifier (e.g. 'TRANSACTION_IMPORTED').", max_length=100)),
                ('metadata', models.JSONField(default=dict, help_text='Arbitrary JSON payload providing event context.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this log entry was created. Set automatically.')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
