# Generated by Django 5.2.12 on 2026-03-09 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this analysis run (UUID v4, auto-generated).', primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(help_text="Analyzer key used for this run (e.g. 'large_transaction').", max_length=100)),
                ('run_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the analysis was executed. Set automatically.')),
                ('results_summary', models.JSONField(help_text="Serialized output dict returned by the Analyzer's run() method.")),
                ('organization', models.ForeignKey(help_text='The organization this analysis was run against.', on_delete=django.db.models.deletion.PROTECT, related_name='analysis_runs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Analysis Run',
                'verbose_name_plural': 'Analysis Runs',
                'ordering': ['-run_time'],
            },
        ),
    ]
