# Generated by Django 5.2.12 on 2026-03-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_status_error_message_nullable_results'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='error_message',
            field=models.TextField(blank=True, help_text='Exception detail captured when status=FAILED. Must be NULL for PENDING and SUCCEEDED runs; must be set for FAILED runs.', null=True),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='results_summary',
            field=models.JSONField(blank=True, help_text="Serialized output dict returned by the Analyzer's run() method. Must be NULL for PENDING and FAILED runs; must be set for SUCCEEDED runs.", null=True),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PENDING'), _negated=True), models.Q(('error_message__isnull', True), ('results_summary__isnull', True)), _connector='OR'), name='analysisrun_pending_fields_null'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'SUCCEEDED'), _negated=True), models.Q(('error_message__isnull', True), ('results_summary__isnull', False)), _connector='OR'), name='analysisrun_succeeded_has_results_no_error'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'FAILED'), _negated=True), models.Q(('error_message__isnull', False), ('results_summary__isnull', True)), _connector='OR'), name='analysisrun_failed_has_error_no_results'),
        ),
    ]
