# Generated by Django 5.2.12 on 2026-03-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_enforce_status_field_invariants'),
        ('organizations', '0003_org_name_unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('organization', 'analysis_type'), name='analysisrun_one_pending_per_org_type'),
        ),
    ]
