# Generated by Django 5.2.12 on 2026-03-19 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_add_security_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this report run (UUID v4, auto-generated).', primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this report run record was created.')),
                ('report_path', models.CharField(blank=True, help_text='Relative path to the generated PDF under REPORT_OUTPUT_DIR.', max_length=500)),
                ('alert_count', models.PositiveIntegerField(default=0, help_text='Number of alerts included in this report.')),
                ('triggered_by', models.CharField(default='manual', help_text="How this report was triggered: 'scheduled' or 'manual'.", max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', help_text='Lifecycle status: PENDING, SUCCEEDED, or FAILED.', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Exception detail if status=FAILED.', null=True)),
                ('organization', models.ForeignKey(help_text='The organization this report was generated for.', on_delete=django.db.models.deletion.PROTECT, related_name='report_runs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Report Run',
                'verbose_name_plural': 'Report Runs',
                'ordering': ['-generated_at'],
            },
        ),
    ]
