# Generated by Django 5.2.12 on 2026-03-09 03:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the organization (UUID v4, auto-generated).', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable name of the organization (e.g. 'Acme Corp').", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the organization record was created. Set automatically.')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
