# Generated by Django 5.2.12 on 2026-03-20 01:37

from django.db import migrations, models
from django.db.models import Count


def resolve_duplicate_org_names(apps, schema_editor):
    """
    Before adding unique=True to Organization.name, ensure no duplicate names
    exist.  For each duplicate group, keep the oldest record (lowest pk order,
    i.e. earliest created) and append '_<n>' suffixes to the newer duplicates.

    The operation is idempotent: re-running it after a partial failure will
    only touch rows that still have a duplicate name.
    """
    Organization = apps.get_model('organizations', 'Organization')

    duplicates = (
        Organization.objects
        .values('name')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    for group in duplicates:
        name = group['name']
        # Order by created_at ascending so the oldest record is kept as-is.
        dupes = list(
            Organization.objects.filter(name=name).order_by('created_at', 'id')
        )
        print(f'[migrate] Duplicate org name "{name}": {len(dupes)} records — keeping pk={dupes[0].id}')
        for n, org in enumerate(dupes[1:], start=2):
            new_name = f'{name}_{n}'
            # Ensure the generated suffix is itself not already taken.
            while Organization.objects.filter(name=new_name).exists():
                n += 1
                new_name = f'{name}_{n}'
            print(f'[migrate]   Renaming pk={org.id} → "{new_name}"')
            org.name = new_name
            org.save(update_fields=['name'])

    # Validate: abort the migration if any duplicates remain.
    remaining = (
        Organization.objects
        .values('name')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    if remaining.exists():
        names = [r['name'] for r in remaining]
        raise RuntimeError(
            f'[migrate] Duplicate org names still present after cleanup: {names}. '
            'Resolve them manually before re-running the migration.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_security_challenge'),
    ]

    operations = [
        migrations.RunPython(resolve_duplicate_org_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text="Human-readable name of the organization (e.g. 'Acme Corp').", max_length=255, unique=True),
        ),
    ]
