# Generated by Django 5.2.12 on 2026-03-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_security_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text="Human-readable name of the organization (e.g. 'Acme Corp').", max_length=255, unique=True),
        ),
    ]
